env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=1
    binary: pxls1
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/heiwa4126/pxls1/cli.Version={{.Version}}
      - -X github.com/heiwa4126/pxls1/cli.Revision={{.ShortCommit}}
    hooks:
        post: upx dist/pxls1_linux_amd64_v1/pxls1
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
